apiVersion: v1
kind: Service
metadata:
  name: flask-load-balancer-service  # Nombre único para el servicio
spec:
  type: NodePort  # Tipo de servicio (NodePort expone el servicio fuera del clúster)
  selector:
    app: flask-load-balancer  # Este selector debe coincidir con el nombre de la etiqueta en el despliegue
  ports:
    - port: 80        # Puerto en el que el servicio será accesible dentro del clúster
      targetPort: 8080 # Puerto donde la aplicación escucha en el contenedor
      nodePort: 30080  # Puerto expuesto en el nodo para acceder externamente (puedes ajustarlo)
