global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'node'

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any time series scraped from this config.
  
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
        - targets: ['prometheus:9090'] # Cambiado para el nombre del servicio de Docker

  - job_name: 'kafka-monitoring'
    scrape_interval: 5s
    static_configs:
        - targets: ['kafka-exporter:9308'] # Cambiado para el nombre del servicio de Docker (kafka)

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100'] # Cambiado para el nombre del servicio de Docker (nodeexporter)

  - job_name: 'python-metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.10.103:8765']  # ✨ Nombre mágico que apunta al host